platform :ios, '7.0'
inhibit_all_warnings!

target 'MVVM' do
  pod 'AFNetworking', '2.1'
  pod 'ReactiveCocoa', '2.2'
  pod 'Mantle', '1.3.1'
  pod 'SVPullToRefresh', '0.4.1'
end

target 'MVVMTests' do
  pod 'OCMock', '2.2.1'
end

